import { v4 as uuidv4 } from 'uuid';
import { JavascriptOutlined } from '@mui/icons-material'; // Replace with actual icons

export const allLanguages = [
  { id: uuidv4(), name: "JavaScript", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Python", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Java", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "C#", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "PHP", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "TypeScript", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "C++", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Ruby", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Swift", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Kotlin", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "R", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Go", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Rust", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Dart", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Scala", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Perl", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Haskell", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "MATLAB", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Shell", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Lua", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "SQL", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Elixir", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Clojure", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Erlang", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Visual Basic", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "F#", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Objective-C", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "COBOL", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
  { id: uuidv4(), name: "Fortran", icon: <JavascriptOutlined sx={{ fontSize: 18 }} /> },
];

export const AllTags = [
    { id: uuidv4(), name: "JavaScript" },
    { id: uuidv4(), name: "Python" },
    { id: uuidv4(), name: "Java" },
    { id: uuidv4(), name: "C++" },
    { id: uuidv4(), name: "HTML" },
    { id: uuidv4(), name: "CSS" },
    { id: uuidv4(), name: "SQL" },
    { id: uuidv4(), name: "Node.js" },
    { id: uuidv4(), name: "React" },
    { id: uuidv4(), name: "Kotlin" },
    { id: uuidv4(), name: "Rust" },
    { id: uuidv4(), name: "TypeScript" },
    { id: uuidv4(), name: "PHP" },
    { id: uuidv4(), name: "Swift" },
    { id: uuidv4(), name: "Ruby" },
    { id: uuidv4(), name: "Go" },
    { id: uuidv4(), name: "Scala" },
    { id: uuidv4(), name: "Perl" },
    { id: uuidv4(), name: "Shell" },
    { id: uuidv4(), name: "Dart" },
    { id: uuidv4(), name: "C#" },
    { id: uuidv4(), name: "Vue.js" },
    { id: uuidv4(), name: "Angular" },
    { id: uuidv4(), name: "Express.js" },
    { id: uuidv4(), name: "MongoDB" },
    { id: uuidv4(), name: "PostgreSQL" },
    { id: uuidv4(), name: "MySQL" },
    { id: uuidv4(), name: "Flutter" },
    { id: uuidv4(), name: "Laravel" },
    { id: uuidv4(), name: "GraphQL" },
  ];
  