import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/assets/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        'custom-gradient': 'linear-gradient(to top, #a8edea 0%, #fed6e3 100%)',

      },
      colors: {
        // Use the CSS variables here in Tailwind's theme
        'base-white': 'var(--color-base-white)',
        'base-black': 'var(--color-base-black)',
        'primary': 'var(--color-primary)',
        'primary-100': 'var(--color-primary-100)',
        'primary-200': 'var(--color-primary-200)',
        'primary-300': 'var(--color-primary-300)',
        'primary-400': 'var(--color-primary-400)',
        'primary-500': 'var(--color-primary-500)',
        'primary-600': 'var(--color-primary-600)',
        'primary-700': 'var(--color-primary-700)',
        'primary-800': 'var(--color-primary-800)',
        'primary-900': 'var(--color-primary-900)',
        'primary-1000': 'var(--color-primary-1000)',
        'secondary': 'var(--color-secondary)',
        'secondary-00': 'var(--color-secondary-00)',
        'secondary-100': 'var(--color-secondary-100)',
        'secondary-200': 'var(--color-secondary-200)',
        'secondary-300': 'var(--color-secondary-300)',
        'secondary-400': 'var(--color-secondary-400)',
        'secondary-500': 'var(--color-secondary-500)',
        'secondary-600': 'var(--color-secondary-600)',
        'secondary-700': 'var(--color-secondary-700)',
        'secondary-800': 'var(--color-secondary-800)',
        'secondary-900': 'var(--color-secondary-900)',
        'secondary-1000': 'var(--color-secondary-1000)',
        'success': 'var(--color-success)',
        'success-100': 'var(--color-success-100)',
        'success-200': 'var(--color-success-200)',
        'success-300': 'var(--color-success-300)',
        'warning': 'var(--color-warning)',
        'warning-100': 'var(--color-warning-100)',
        'warning-200': 'var(--color-warning-200)',
        'warning-300': 'var(--color-warning-300)',
        'error': 'var(--color-error)',
        'error-100': 'var(--color-error-100)',
        'error-200': 'var(--color-error-200)',
        'error-300': 'var(--color-error-300)',
        'neutrals-100': 'var(--color-neutrals-100)',
        'neutrals-200': 'var(--color-neutrals-200)',
        'neutrals-300': 'var(--color-neutrals-300)',
        'neutrals-400': 'var(--color-neutrals-400)',
        'neutrals-500': 'var(--color-neutrals-500)',
        'neutrals-600': 'var(--color-neutrals-600)',
        'neutrals-700': 'var(--color-neutrals-700)',
        'neutrals-800': 'var(--color-neutrals-800)',
        'neutrals-900': 'var(--color-neutrals-900)',
        'neutrals-1000': 'var(--color-neutrals-1000)',
        'main-500':'var(--color-main-500)',
        'border': 'var(--color-border)',
      },
      spacing: {
        'base': 'var(--size-base)',
        'xxs': 'var(--size-xxs)',
        'xs': 'var(--size-xs)',
        's': 'var(--size-s)',
        'sm': 'var(--size-sm)',
        'm': 'var(--size-m)',
        'ml': 'var(--size-ml)',
        'l': 'var(--size-l)',
        'xl': 'var(--size-xl)',
      },
      fontSize: {
        'h1': 'var(--heading-1-font-size)',
        'h2': 'var(--heading-2-font-size)',
        'h3': 'var(--heading-3-font-size)',
        'h4': 'var(--heading-4-font-size)',
        'h5': 'var(--heading-5-font-size)',
        'h1-desktop': 'var(--heading-1-desktop-font-size)',
        'h2-desktop': 'var(--heading-2-desktop-font-size)',
        'h3-desktop': 'var(--heading-3-desktop-font-size)',
        'h4-desktop': 'var(--heading-4-desktop-font-size)',
        'b1': 'var(--body-1-font-size)',
        'b2': 'var(--body-2-font-size)',
        'b3': 'var(--body-3-font-size)',
        'b4': 'var(--body-4-font-size)',
        'b1-desktop': 'var(--body-1-desktop-font-size)',
        'b2-desktop': 'var(--body-2-desktop-font-size)',
        'b3-desktop': 'var(--body-3-desktop-font-size)',
        'd1': 'var(--display-1-font-size)',
        'd2': 'var(--display-2-font-size)',
        'd3': 'var(--display-3-font-size)',
      },
      fontWeight: {
        'h1': 'var(--heading-1-font-weight)',
        'h2': 'var(--heading-2-font-weight)',
        'h3': 'var(--heading-3-font-weight)',
        'h4': 'var(--heading-4-font-weight)',
        'h5': 'var(--heading-5-font-weight)',
        'h1-desktop': 'var(--heading-1-desktop-font-weight)',
        'h2-desktop': 'var(--heading-2-desktop-font-weight)',
        'h3-desktop': 'var(--heading-3-desktop-font-weight)',
        'h4-desktop': 'var(--heading-4-desktop-font-weight)',
        'b1': 'var(--body-1-font-weight)',
        'b2': 'var(--body-2-font-weight)',
        'b3': 'var(--body-3-font-weight)',
        'b4': 'var(--body-4-font-weight)',
        'b1-desktop': 'var(--body-1-desktop-font-weight)',
        'b2-desktop': 'var(--body-2-desktop-font-weight)',
        'b3-desktop': 'var(--body-3-desktop-font-weight)',
        'd1': 'var(--display-1-font-weight)',
        'd2': 'var(--display-2-font-weight)',
        'd3': 'var(--display-3-font-weight)',
      },
      lineHeight: {
        'h1': 'var(--heading-1-line-height)',
        'h2': 'var(--heading-2-line-height)',
        'h3': 'var(--heading-3-line-height)',
        'h4': 'var(--heading-4-line-height)',
        'h5': 'var(--heading-5-line-height)',
        'h1-desktop': 'var(--heading-1-desktop-line-height)',
        'h2-desktop': 'var(--heading-2-desktop-line-height)',
        'h3-desktop': 'var(--heading-3-desktop-line-height)',
        'h4-desktop': 'var(--heading-4-desktop-line-height)',
        'b1': 'var(--body-1-line-height)',
        'b2': 'var(--body-2-line-height)',
        'b3': 'var(--body-3-line-height)',
        'b4': 'var(--body-4-line-height)',
        'b1-desktop': 'var(--body-1-desktop-line-height)',
        'b2-desktop': 'var(--body-2-desktop-line-height)',
        'b3-desktop': 'var(--body-3-desktop-line-height)',
        'd1': 'var(--display-1-line-height)',
        'd2': 'var(--display-2-line-height)',
        'd3': 'var(--display-3-line-height)',
      },
      screens: {
        'sm': '640px',
  
        'md': '768px',
  
        'lg': '1024px',
  
        'xl': '1440px',
  
        '2xl': '1920px',
      }
    },
  },
  plugins: [],
};
export default config;
