import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import {bodyBgImage} from "../assets/index"
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import GlobalContextProvider from "@/ContextApi";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <GlobalContextProvider>
          <body  className={poppins.className}>
            {children}
          </body>
        </GlobalContextProvider>
      </html>
    </ClerkProvider>
  );
}
